// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace LearnTop.Modules.Identity.Infrastructure.Data.WriteDb.Migrations
{
    /// <inheritdoc />
    public partial class AddDisplayNameToUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("0aae8209-417a-4aa9-87ea-1eae29f17a1c"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("c370d992-a181-4d86-a8c3-3c516102880a"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("d93d26f9-7c2f-4f98-bae1-c27a0f2ecfda"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("eb10266b-07cd-41ff-b7f1-f4afc1f5c538"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("11c6e82a-5a4b-48ed-a3da-c62f50e85812"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("80649c43-91b5-406e-8059-3eefadff94b5"));

            migrationBuilder.AddColumn<string>(
                name: "DisplayName",
                schema: "Identity",
                table: "Users",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Permissions",
                columns: new[] { "Id", "Application", "Description", "Type" },
                values: new object[,]
                {
                    { new Guid("9bedba52-4bd4-45de-91da-f778ce90d684"), "Tags", "حذف تگ ها", "Delete" },
                    { new Guid("bdd0241e-9096-4537-bb1a-2c63bba10572"), "Articles", "ایجاد مقالات", "Write" },
                    { new Guid("f6a8f6b4-425d-4ad2-ae1e-61d86f7e6ca7"), "Articles", "خواندن مقالات", "Read-Deleted" },
                    { new Guid("f8f8e9f4-4a7e-4518-85a9-1d8fdf7ed618"), "Tags", "ایجاد تگ های جدید", "Write" }
                });

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Roles",
                columns: new[] { "Id", "CreatedAt", "DeletedAt", "IsActive", "Name", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("34cdc888-239c-42c3-b4d6-2a40f79ebf72"), new DateTime(2025, 4, 25, 18, 57, 6, 74, DateTimeKind.Local).AddTicks(5332), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "Admin", new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2747) },
                    { new Guid("8a59652a-308c-43eb-a420-d0adb1ca1cb2"), new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2786), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "User", new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2786) }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("9bedba52-4bd4-45de-91da-f778ce90d684"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("bdd0241e-9096-4537-bb1a-2c63bba10572"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("f6a8f6b4-425d-4ad2-ae1e-61d86f7e6ca7"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("f8f8e9f4-4a7e-4518-85a9-1d8fdf7ed618"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("34cdc888-239c-42c3-b4d6-2a40f79ebf72"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("8a59652a-308c-43eb-a420-d0adb1ca1cb2"));

            migrationBuilder.DropColumn(
                name: "DisplayName",
                schema: "Identity",
                table: "Users");

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Permissions",
                columns: new[] { "Id", "Application", "Description", "Type" },
                values: new object[,]
                {
                    { new Guid("0aae8209-417a-4aa9-87ea-1eae29f17a1c"), "Articles", "ایجاد مقالات", "Write" },
                    { new Guid("c370d992-a181-4d86-a8c3-3c516102880a"), "Articles", "خواندن مقالات", "Read-Deleted" },
                    { new Guid("d93d26f9-7c2f-4f98-bae1-c27a0f2ecfda"), "Tags", "ایجاد تگ های جدید", "Write" },
                    { new Guid("eb10266b-07cd-41ff-b7f1-f4afc1f5c538"), "Tags", "حذف تگ ها", "Delete" }
                });

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Roles",
                columns: new[] { "Id", "CreatedAt", "DeletedAt", "IsActive", "Name", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("11c6e82a-5a4b-48ed-a3da-c62f50e85812"), new DateTime(2025, 2, 8, 17, 34, 45, 738, DateTimeKind.Local).AddTicks(6778), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "Admin", new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4319) },
                    { new Guid("80649c43-91b5-406e-8059-3eefadff94b5"), new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4358), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "User", new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4359) }
                });
        }
    }
}
