// <auto-generated />
using System;
using LearnTop.Modules.Identity.Infrastructure.Data.WriteDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnTop.Modules.Identity.Infrastructure.Data.WriteDb.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20250201072850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Roles.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03947f04-566f-4a60-86f3-0ce179e9097a"),
                            Application = "Articles",
                            Description = "دسترسی به خواندن مقالات",
                            Type = "Read-Deleted"
                        },
                        new
                        {
                            Id = new Guid("7bda802b-9a72-427c-80b4-1d1b09229da1"),
                            Application = "Articles",
                            Description = "ایجاد تغییر در مقالات",
                            Type = "Write"
                        });
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Roles.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be329f75-5e81-45ab-9e79-fd501e2eb5da"),
                            CreatedAt = new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4121),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4122)
                        },
                        new
                        {
                            Id = new Guid("36172c34-0dd8-4280-bc2a-68ff0d68f53f"),
                            CreatedAt = new DateTime(2025, 2, 1, 10, 58, 50, 57, DateTimeKind.Local).AddTicks(6545),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4093)
                        });
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Address");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Email", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Number");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mobile", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Identity");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionRole", "Identity");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Email", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithOne("Email")
                        .HasForeignKey("LearnTop.Modules.Identity.Domain.Users.Models.Email", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LearnTop.Modules.Identity.Domain.Users.ValueObjects.Verify", "Verify", b1 =>
                        {
                            b1.Property<Guid>("EmailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Code")
                                .HasColumnType("int")
                                .HasColumnName("Code");

                            b1.Property<DateTime>("ExpireIn")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpireIn");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit")
                                .HasColumnName("Status");

                            b1.HasKey("EmailId");

                            b1.ToTable("Email", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("EmailId");
                        });

                    b.Navigation("Verify")
                        .IsRequired();
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithOne("Mobile")
                        .HasForeignKey("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LearnTop.Modules.Identity.Domain.Users.ValueObjects.Verify", "Verify", b1 =>
                        {
                            b1.Property<Guid>("MobileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Code")
                                .HasColumnType("int")
                                .HasColumnName("Code");

                            b1.Property<DateTime>("ExpireIn")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpireIn");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit")
                                .HasColumnName("Status");

                            b1.HasKey("MobileId");

                            b1.ToTable("Mobile", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("MobileId");
                        });

                    b.Navigation("Verify")
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.User", b =>
                {
                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Mobile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
