// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace LearnTop.Modules.Identity.Infrastructure.Data.WriteDb.Migrations
{
    /// <inheritdoc />
    public partial class AddNewPermissions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("03947f04-566f-4a60-86f3-0ce179e9097a"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("7bda802b-9a72-427c-80b4-1d1b09229da1"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("36172c34-0dd8-4280-bc2a-68ff0d68f53f"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("be329f75-5e81-45ab-9e79-fd501e2eb5da"));

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Permissions",
                columns: new[] { "Id", "Application", "Description", "Type" },
                values: new object[,]
                {
                    { new Guid("0aae8209-417a-4aa9-87ea-1eae29f17a1c"), "Articles", "ایجاد مقالات", "Write" },
                    { new Guid("c370d992-a181-4d86-a8c3-3c516102880a"), "Articles", "خواندن مقالات", "Read-Deleted" },
                    { new Guid("d93d26f9-7c2f-4f98-bae1-c27a0f2ecfda"), "Tags", "ایجاد تگ های جدید", "Write" },
                    { new Guid("eb10266b-07cd-41ff-b7f1-f4afc1f5c538"), "Tags", "حذف تگ ها", "Delete" }
                });

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Roles",
                columns: new[] { "Id", "CreatedAt", "DeletedAt", "IsActive", "Name", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("11c6e82a-5a4b-48ed-a3da-c62f50e85812"), new DateTime(2025, 2, 8, 17, 34, 45, 738, DateTimeKind.Local).AddTicks(6778), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "Admin", new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4319) },
                    { new Guid("80649c43-91b5-406e-8059-3eefadff94b5"), new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4358), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "User", new DateTime(2025, 2, 8, 17, 34, 45, 739, DateTimeKind.Local).AddTicks(4359) }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("0aae8209-417a-4aa9-87ea-1eae29f17a1c"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("c370d992-a181-4d86-a8c3-3c516102880a"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("d93d26f9-7c2f-4f98-bae1-c27a0f2ecfda"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Permissions",
                keyColumn: "Id",
                keyValue: new Guid("eb10266b-07cd-41ff-b7f1-f4afc1f5c538"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("11c6e82a-5a4b-48ed-a3da-c62f50e85812"));

            migrationBuilder.DeleteData(
                schema: "Identity",
                table: "Roles",
                keyColumn: "Id",
                keyValue: new Guid("80649c43-91b5-406e-8059-3eefadff94b5"));

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Permissions",
                columns: new[] { "Id", "Application", "Description", "Type" },
                values: new object[,]
                {
                    { new Guid("03947f04-566f-4a60-86f3-0ce179e9097a"), "Articles", "دسترسی به خواندن مقالات", "Read-Deleted" },
                    { new Guid("7bda802b-9a72-427c-80b4-1d1b09229da1"), "Articles", "ایجاد تغییر در مقالات", "Write" }
                });

            migrationBuilder.InsertData(
                schema: "Identity",
                table: "Roles",
                columns: new[] { "Id", "CreatedAt", "DeletedAt", "IsActive", "Name", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("36172c34-0dd8-4280-bc2a-68ff0d68f53f"), new DateTime(2025, 2, 1, 10, 58, 50, 57, DateTimeKind.Local).AddTicks(6545), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "Admin", new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4093) },
                    { new Guid("be329f75-5e81-45ab-9e79-fd501e2eb5da"), new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4121), new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), false, "User", new DateTime(2025, 2, 1, 10, 58, 50, 58, DateTimeKind.Local).AddTicks(4122) }
                });
        }
    }
}
