// <auto-generated />
using System;
using LearnTop.Modules.Identity.Infrastructure.Data.WriteDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnTop.Modules.Identity.Infrastructure.Data.WriteDb.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Roles.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a8f6b4-425d-4ad2-ae1e-61d86f7e6ca7"),
                            Application = "Articles",
                            Description = "خواندن مقالات",
                            Type = "Read-Deleted"
                        },
                        new
                        {
                            Id = new Guid("bdd0241e-9096-4537-bb1a-2c63bba10572"),
                            Application = "Articles",
                            Description = "ایجاد مقالات",
                            Type = "Write"
                        },
                        new
                        {
                            Id = new Guid("f8f8e9f4-4a7e-4518-85a9-1d8fdf7ed618"),
                            Application = "Tags",
                            Description = "ایجاد تگ های جدید",
                            Type = "Write"
                        },
                        new
                        {
                            Id = new Guid("9bedba52-4bd4-45de-91da-f778ce90d684"),
                            Application = "Tags",
                            Description = "حذف تگ ها",
                            Type = "Delete"
                        });
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Roles.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a59652a-308c-43eb-a420-d0adb1ca1cb2"),
                            CreatedAt = new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2786),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2786)
                        },
                        new
                        {
                            Id = new Guid("34cdc888-239c-42c3-b4d6-2a40f79ebf72"),
                            CreatedAt = new DateTime(2025, 4, 25, 18, 57, 6, 74, DateTimeKind.Local).AddTicks(5332),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 4, 25, 18, 57, 6, 75, DateTimeKind.Local).AddTicks(2747)
                        });
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Address");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Email", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Number");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mobile", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Identity");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionRole", "Identity");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser", "Identity");
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Email", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithOne("Email")
                        .HasForeignKey("LearnTop.Modules.Identity.Domain.Users.Models.Email", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LearnTop.Modules.Identity.Domain.Users.ValueObjects.Verify", "Verify", b1 =>
                        {
                            b1.Property<Guid>("EmailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Code")
                                .HasColumnType("int")
                                .HasColumnName("Code");

                            b1.Property<DateTime>("ExpireIn")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpireIn");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit")
                                .HasColumnName("Status");

                            b1.HasKey("EmailId");

                            b1.ToTable("Email", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("EmailId");
                        });

                    b.Navigation("Verify")
                        .IsRequired();
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithOne("Mobile")
                        .HasForeignKey("LearnTop.Modules.Identity.Domain.Users.Models.Mobile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LearnTop.Modules.Identity.Domain.Users.ValueObjects.Verify", "Verify", b1 =>
                        {
                            b1.Property<Guid>("MobileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Code")
                                .HasColumnType("int")
                                .HasColumnName("Code");

                            b1.Property<DateTime>("ExpireIn")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpireIn");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit")
                                .HasColumnName("Status");

                            b1.HasKey("MobileId");

                            b1.ToTable("Mobile", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("MobileId");
                        });

                    b.Navigation("Verify")
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("LearnTop.Modules.Identity.Domain.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTop.Modules.Identity.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnTop.Modules.Identity.Domain.Users.Models.User", b =>
                {
                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Mobile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
